### ISSUE TITLE
this module is not compatible with nginx v1-24-0

### ISSUE THREAD

**Issue by ghost** [Refinitiv/nginx-sticky-module-ng#14]
Hi,
I want to make nginx 1-24-0 using nginx-sticky-module-ng. but it has some errors:
1- error: ‘ngx_http_headers_in_t’ has no member named ‘cookies’; did you mean ‘cookie’?
  243 |         if (ngx_http_parse_multi_header_lines(&r->headers_in.cookies, &iphp->sticky_conf->cookie_name, &route) != NGX_DECLINED) {
2- error: passing argument 2 of ‘ngx_http_parse_multi_header_lines’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  243 |         if (ngx_http_parse_multi_header_lines(&r->headers_in.cookies, &iphp->sticky_conf->cookie_name, &route) != NGX_DECLINED) {
3- error: too few arguments to function ‘ngx_http_parse_multi_header_lines’
  243 |         if (ngx_http_parse_multi_header_lines(&r->headers_in.cookies, &iphp->sticky_conf->cookie_name, &route) != NGX_DECLINED) {
4- error: ‘ngx_http_upstream_headers_in_t’ has no member named ‘cookies’
  475 |                 if (ngx_http_parse_set_cookie_lines(&r->upstream->headers_in.cookies, &ctx->sticky_conf->cookie_name, &transfer_cookie) == NGX_DECLINED)
5- error: passing argument 2 of ‘ngx_http_parse_set_cookie_lines’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  475 |                 if (ngx_http_parse_set_cookie_lines(&r->upstream->headers_in.cookies, &ctx->sticky_conf->cookie_name, &transfer_cookie) == NGX_DECLINED)
6- error: too few arguments to function ‘ngx_http_parse_set_cookie_lines’
  475 |                 if (ngx_http_parse_set_cookie_lines(&r->upstream->headers_in.cookies, &ctx->sticky_conf->cookie_name, &transfer_cookie) == NGX_DECLINED)

in https://trac.nginx.org/nginx/ticket/2358 an error like the errors that are mentioned here is investigated. ( This includes the explicitly mentioned change to use linked lists instead of arrays, as well as various renames to match the new approach to headers. For the details about the particular change causing the build failure, see [ef6a3a99a81a](https://trac.nginx.org/nginx/changeset/ef6a3a99a81a/). The 3rd party modules you are using need to be adjust to work with nginx 1.23.0.)
 
I need to have this module with nginx. if it is possible, please resolve it. thank you.

**Comment by Gokul-Rams** [comment]
I am also facing same issue when building nginx image with nginx version post 1.23 
Is there any possibility of fixing this issue providing compatability with latest nginx versions

**Comment by rickygm** [comment]
does not compile with nginx 1.24:

c1: all warnings being treated as errors
make[1]: *** [objs/Makefile:2226: objs/addon/nginx-sticky-module-ng/ngx_http_sticky_module.o] Error 1
make[1]: Leaving directory '/rpm/nginx-1.24.0'
make: *** [Makefile:10: build] Error 2

**Comment by xuges** [comment]
@ssh81  This issue was resolved on my fork: https://github.com/xu2ge/nginx-sticky-module-ng
you also can see my pull request: https://github.com/Refinitiv/nginx-sticky-module-ng/pull/17

**Comment by rickygm** [comment]
works perfect my friend

**Comment by ghost** [comment]
> @ssh81 This issue was resolved on my fork: https://github.com/xu2ge/nginx-sticky-module-ng you also can see my pull request: #17

Thank you :)

**Comment by devhaozi** [comment]
@Refinitiv Can you please check and merge this fix?
@JonathanHuot @vkaidalov-rft
